VIDEO_PATH: 'E:\\t_map\\Sample 8\\500.MOV'  # 视频地址,文件名、路径不要中文，下同
mainDir: 'E:\\t_map\\extract_data\\500' #每个工况一个文件夹，每次换工况（或者认为是换视频）就新建一个数字然后改这里

imgDir: 'image/' #RGB图像保存文件夹

cornerPath: 'E:/t_map/extract_data/1_old/corner_points.csv' #角点存取路径，认为各个工况下设备位姿不变（角点一致）
alignTxtPath: 'E:/t_map/extract_data/1_old/alignment_recorder.txt' #增加一个txt文件，记录时间标定的数据

csvDir: "csv/" #热成像仪csv文件的读取文件夹
tempDir: "temp/" #临时图像的保存
savePointsDir: "points/" #输出的点保存的文件夹
txtPath: "recorder.txt" #记录用的

dstPoint: 1000  # 透视变化用的，变换目标大小
n: 14 #点阵行列数

x: 1 # 每隔x个csv取一个